export const myProjects = [
  {
    name: "Real Time Chat",
    img: "chatapp",
    link: "https://github.com/Dwifakhri/chat-app",
    desc: "A web application is used to personal chat in real time. Its feature can join or leave group with other users. Its providing a fluid and responsive chat experience.",
    stack: ["vue", "bootstrap", "express"],
  },
  {
    name: "Meeting Transcript",
    img: "transcript",
    link: "https://transcript.netray.id/",
    desc: "A web application is used to process the transcribing and managing meeting notes. It uses to convert source audio file into text (speech-to-text) into accurate result.",
    stack: ["nuxt js", "bootstrap", "rest"],
  },
  {
    name: "Bantul Mapan",
    img: "siekodig",
    link: "https://bantulmapan.kab-bantul.id/",
    desc: "A web application which aims to analyze and present statistical data of Micro, Small, and Medium Enterprises (MSMEs) in Bantul District, Indonesia.",
    stack: ["nuxt js", "bootstrap", "rest"],
  },
  {
    name: "CV Generator",
    img: "cvgen",
    link: "https://cv-builder-jade.vercel.app/",
    desc: "A web application is used to create an ATS resume or curriculum vitae. It assists users in creating professional resumes or CVs tailored to their specific needs",
    stack: ["vue", "bootstrap", "localstorage"],
  },
  {
    name: "Mentutor",
    img: "mentutor",
    link: "https://github.com/Dwifakhri/Mentutor",
    desc: "A web application which user can manage the task or submission for mentor and mentee. It helps to monitor the students report/activity for mentor and easy to use.",
    stack: ["react js", "tailwind", "rest"],
  },
  {
    name: "Nouncer",
    img: "nouncer",
    link: "https://nouncer-app.vercel.app/",
    desc: "A web application for finding the mean of the word like dictionary. Dive into a world of words, definitions, synonyms, antonyms, and more, curated to enhance your understanding and appreciation of language.",
    stack: ["react js", "tailwind", "rest"],
  },
  {
    name: "Movies21",
    img: "movies21",
    link: "https://movies21-five.vercel.app/",
    desc: "A web application that user can see the popular movies in a list. Explore an extensive library of films, discover hidden gems, and stay up-to-date with the latest releases, all from the comfort of your web browser. ",
    stack: ["react js", "tailwind", "rest"],
  },
  {
    name: "Pokemon Gatcha",
    img: "poke",
    link: "https://pokemon-app-mauve.vercel.app/",
    desc: "A web application that user can catch the pokemon as a game. Many pokemons that you can catch and collect into favorites pokemon",
    stack: ["react js", "tailwind", "rest"],
  },
]
